### ISSUE TITLE
log.SetLogger(...) was never called; logs will not be displayed.

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#1063]
OFO v0.5.2 w/ flagd-proxy v0.3.2 installed via argo (helm)

```
		 ______   __       ________   _______    ______
		/_____/\ /_/\     /_______/\ /______/\  /_____/\
		\::::_\/_\:\ \    \::: _  \ \\::::__\/__\:::_ \ \
		 \:\/___/\\:\ \    \::(_)  \ \\:\ /____/\\:\  \ \ \
		  \:::._\/ \:\ \____\:: __  \ \\:\\_  _\/ \:\ \ \ \
		   \:\ \    \:\/___/\\:.\ \  \ \\:\_\ \ \  \:\/.:| |
		    \_\/     \_____\/ \__\/\__\/ \_____\/   \____/_/
		                                   Kubernetes Proxy

2023-12-06T23:10:35.271Z	info	cmd/start.go:99	listening for connections on 8015
2023-12-06T23:10:35.271Z	info	sync/server.go:108	binding metrics to 8016
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 57 [running]:
	>  runtime/debug.Stack()
	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc00013d9c0, {0x192fee6, 0x14})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:147 +0x45
	>  github.com/go-logr/logr.Logger.WithName({{0x1bc01f0, 0xc00013d9c0}, 0x0}, {0x192fee6?, 0xc0002f0000?})
	>  	/go/pkg/mod/github.com/go-logr/logr@v1.3.0/logr.go:349 +0x3d
	>  sigs.k8s.io/controller-runtime/pkg/client.newClient(0x0?, {0x0, 0xc0003aa7e0, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/client.go:122 +0xec
	>  sigs.k8s.io/controller-runtime/pkg/client.New(0x7f16dabb7108?, {0x0, 0xc0003aa7e0, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/client.go:103 +0x7d
	>  github.com/open-feature/flagd/core/pkg/sync/kubernetes.GetClients()
	>  	/src/core/pkg/sync/kubernetes/kubernetes_sync.go:64 +0x85
	>  github.com/open-feature/flagd/core/pkg/runtime.NewK8s({0xc0001d81e0, 0x49}, 0xc0001e9c50)
	>  	/src/core/pkg/runtime/from_config.go:247 +0x37
	>  github.com/open-feature/flagd/core/pkg/sync-store.(*SyncBuilder).SyncFromURI(0x16ec100?, {0xc0001d81e0, 0x49}, 0xc00027a570)
	>  	/src/core/pkg/sync-store/sync_store.go:290 +0x8b7
	>  github.com/open-feature/flagd/core/pkg/sync-store.(*SyncStore).watchResource(0xc000050940, {0xc0001d81e0, 0x49})
	>  	/src/core/pkg/sync-store/sync_store.go:190 +0x274
	>  created by github.com/open-feature/flagd/core/pkg/sync-store.(*SyncStore).RegisterSubscription in goroutine 56
	>  	/src/core/pkg/sync-store/sync_store.go:127 +0x525
2023-12-06T23:11:33.011Z	info	kubernetes/kubernetes_sync.go:111	starting kubernetes sync notifier for resource: openfeatureplayground-team70-preprod-cd/sample-flags	{"component": "sync", "sync": "kubernetes"}
```

**Comment by bacherfl** [comment]
It seems like this is happening because the kubernetes sync of the flagd-proxy is using the `k8s.io/controller-runtime` client, which is intended to be used in an operator, such as the OF operator. The controller runtime has the requirement of the `log.SetLogger()` function to be called within 30 seconds after the application has been started (see [1]), otherwise the error message will be shown. I just verified this be starting `flagd-proxy`, waiting 30 seconds, and then doing a call to `SyncFlags`, resulting in the message being shown. If `SyncFlags` is called within 30 seconds, no error message is printed.

This however does not affect the logging of the `flagd-proxy`, as can also be seen in the log posted in the issue description. Only the logs generated by the controller runtime will not be displayed, but since the proxy is not an operator this does not have an effect.

To get rid of this error message we would need to make sure the said `log.SetLogger()` function is called during startup of `flagd-proxy`. However, I would recommend to switch to the client go [2] library instead, as this is more intended for this kind of application, whereas using the client from the controller-runtime is a bit of a misuse in this setting.
Switching to the `client-go` library will require making some changes in the usage of the client, but could be done with relatively low effort imho.

References:

[1] - https://github.com/kubernetes-sigs/controller-runtime/blob/1ea2be573f7887a9fbd766e9a921c5af344da6eb/pkg/log/log.go#L78
[2] - https://github.com/kubernetes/client-go

**Comment by beeme1mr** [comment]
Thanks for the detailed explanation @bacherfl. Should a separate issue be opened for switching libraries?

**Comment by toddbaert** [comment]
I've created an issue [here](https://github.com/open-feature/flagd/issues/1072) with a clear goal to change this.
