### ISSUE TITLE
[CHORE] Add Connect-Protocol-Version to Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by james-milligan** [open-feature/flagd#232]
### Requirements

The `Connect-Protocol-Version` value needs to be added to the `Access-Control-Allow-Headers` in the service header configuration to maintain there is compatibility with browsers

https://github.com/bufbuild/connect-go/releases/tag/v1.4.0

**Comment by beeme1mr** [comment]
Hey @james-milligan, is this issue still valid? If so, could you please make sure the requirements as clear and add a `good first issue` label?

**Comment by craigpastro** [comment]
Hello 👋 I was hoping to help out with this one. I took a quick look and noticed that you already use `*` for the `Access-Control-Allow-Headers` value. https://github.com/open-feature/flagd/blob/09c0198f76a200b1b6a1f48e9c94ec0547283ca2/core/pkg/service/middleware/cors/cors.go#L25

So, I suppose since requests to flagd are without credentials, this is fine and there is no need to add `Connect-Protocol-Version` to that list explicitly? Or is this wrong?

Thanks!

**Comment by toddbaert** [comment]
@craigpastro I've looked into this and I think you're exactly correct, and this is not needed.

Thanks for pointing this out. I move we close this, unless somebody else disagrees or can point out what @craigpastro and I are missing.

cc @beeme1mr @bacherfl @james-milligan @thisthat
