### ISSUE TITLE
[BUG] Release artifacts include space character in download

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#511]
### Observed behavior

The release artifacts now include a space character: `%2F` which is a breaking change and renders any existing download scripts that people have written to be invalid.

For example,

```
https://github.com/open-feature/flagd/releases/download/v0.4.0/flagd_0.4.0_Linux_x86_64.tar.gz
```
Is now:
```
https://github.com/open-feature/flagd/releases/download/flagd%2Fv0.4.4/flagd_0.4.4_Linux_x86_64.tar.gz
```

Note the `_` has changed to a `%2F`

**Comment by beeme1mr** [comment]
Hey @agardnerIT, this is a side effect of the recent monorepo change. Basically, multiple artifacts are now released from the same repo. Due to this, the git tag needs a prefix. In this case, the prefix is `flagd/` which is URL encoded to `flagd%2F`.

You can see a list of the new tags [here](https://github.com/open-feature/flagd/tags). Please update your scripts to absorb this change. It should be a one-time change.
