### ISSUE TITLE
Metric for evaluations by reason (including errors)

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#559]
We should create a new metric which buckets _evaluations by reason_, which would include evaluations that failed because they were not found flags, or evaluations which had un-parsable context, or other error conditions, as well as flags that evaluated some way due to targeting vs static assignment, etc.

Created based on [this](https://github.com/open-feature/flagd/pull/556#discussion_r1147789139) (cc @beeme1mr @thisthat )

**Comment by thisthat** [comment]
To continue the discussion based on the [PR](https://github.com/open-feature/flagd/pull/556#discussion_r1147789139), I agree to have this information, but I don't know if a whole new metric makes sense. We could add the reason in a new dimension `feature_flag_reason` without the need to set up a whole new metric pipeline. With the concern about metric explosion due to the use of invalid flag keys, we could bucket these faulty evaluations under the dimension `feature_flag_key=flagd_error`.
WDYT @toddbaert, @beeme1mr ?

**Comment by beeme1mr** [comment]
I think that impressions should only be captured for valid feature flags. Creating a hard-coded error dimension would likely work but seems like a [magic string](https://en.wikipedia.org/wiki/Magic_string). What would happen if someone named their feature `flagd_error` 🤣.

What's the disadvantage of adding a new metric? Perhaps the metric could be focused entirely on error conditions instead of capturing all reasons. Being able to chart errors like "flag not found" over time would be very valuable.

**Comment by toddbaert** [comment]
>Perhaps the metric could be focused entirely on error conditions instead of capturing all reasons.

Isn't seeing reasons also really valuable though `STATIC` (cachable) vs `TARGET_MATCH` vs `ERROR (and error details)`. I see only upsides to all this info.

**Comment by toddbaert** [comment]
@thisthat and I spoke about this and I think we agree that a new metric that contains reasons (including `ERROR`) as well as data about the error (`FLAG_NOT_FOUND`) makes sense.

Use cases this supports:

- understanding performance (eg: lots of `STATIC` evaluation means more caching may be possible)
- understanding configuration errors (eg: a sudden spike in `ERROR`s of type `FLAG_NOT_FOUND` means a new evaluation has been deployed ahead of its definition)
- finding bugs (a client is sending an invalid context)
