### ISSUE TITLE
Migrate to Go 1.18

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#58]
[Kubebuilder now supports Go 1.18](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.5.0). With this, it might be a good time to update both the operator and flagd to 1.18. I'm particularly excited for the possibility of using generics to greatly simplify flagd.

**Comment by AlexsJones** [comment]
Upgrading to 1.18 is one thing, moving to generics is another. 
Let's do some research before we just jump to generics because they are new. Templating in C++ is an absolute nightmare to debug. I am not against it but think we need to have some solid research and examples of what we want to replace.

**Comment by AlexsJones** [comment]
https://github.com/open-feature/flagd/pull/59/ this should enable 1.18

**Comment by moshebe** [comment]
I think this one is already handled. @AlexsJones @toddbaert
