### ISSUE TITLE
[BUG] Changes in observed FeatureFlagConfigs are not propagated to the EventStream with v0.5.0

### ISSUE THREAD

**Issue by bacherfl** [open-feature/flagd#603]
### Observed behavior

When using v0.5.0 of Flagd in a `FlagSourceConfiguration` - see https://github.com/open-feature/cloud-native-demo/blob/main/deployment/flagd-flag-spec.yaml - changes in the referenced FeatureFlagConfigurations do not cause a `configuration_change` event to be sent to the EventStream. `provider_ready` and `keep_alive` events are received by the client.
When setting the flagd version to 0.4.4, changes to a FeatureFlagConfiguration are propagated to the EventStream as expected.

### Expected Behavior

When updating a `FeatureFlagConfiguration`custom resource referenced in the `--uri` argument, this should result in a `configuration_change` event to be sent to the subscribed clients.

### Steps to reproduce

1. Run flagd with a kubernetes sync source, e.g.:

```
flagd start --uri=core.openfeature.dev/open-feature-demo/client-side
```

2. Subscribe to the eventStream with a grpc client
3. Change the observed FeatureFlagConfiguration `client-side`
4. Observe the EventStream - `provider_ready` and `keep_alive` events are received, but no `configuration_change` events are sent by flagd

**Comment by Kavindu-Dodan** [comment]
The root cause is a misconfiguration 

flag evaluator contains a dedicated `eventingConfiguration` [1] which is not reflected at connect_service [2]

[1] - https://github.com/open-feature/flagd/blob/main/core/pkg/service/flag-evaluation/flag_evaluator.go#L40-L42
[2] -https://github.com/open-feature/flagd/blob/main/core/pkg/service/flag-evaluation/connect_service.go#L46-L48
