### ISSUE TITLE
[FEATURE] Release windows binaries as ZIP not tar.gz

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#639]
### Requirements

This issue proposes that we `.zip` files for windows instead of `.tar.gz`ing them.

**Comment by Kavindu-Dodan** [comment]
Good point. Right now we perform .tar.gz for all binaries [1]. But, yes it makes sense to release .zip for windows 

@toddbaert  any input ? Otherwise, I can work on this through https://github.com/open-feature/flagd/issues/581 as I already will be working on GH releas action. 

[1] - https://github.com/open-feature/flagd/blob/main/.github/workflows/release-please.yaml#L192-L198

**Comment by toddbaert** [comment]
I haven't used Windows as a daily driver for quite a few years, so I'm probably not the best person to ask. If people aren't using WSL I guess it'd make sense that they'd prefer a .zip?

**Comment by Kavindu-Dodan** [comment]
I used Windows and usually `.zip` works best there. The alternative here is to rely on an installation like `7-zip` but this could be limited in restricted systems.

**Comment by Kavindu-Dodan** [comment]
This is fixed with PR #642
