### ISSUE TITLE
[FEATURE] Evaluating multiple flags as one batch concurrently

### ISSUE THREAD

**Issue by yangzhaox** [open-feature/flagd#961]
### Requirements

In our team we have a need to evaluate multiple flags, e.g. 15 of 30 concurrently by specifying the list of flag names, and ideally each flag evaluation goes into a goroutine so the overall latency would be still fast enough. By reading the documentation, I could not find this api, the only relevant one is resolveAll but it's not what we need. Would you consider to support this use case? Thanks.

**Comment by yangzhaox** [comment]
Hi @toddbaert, thanks for your reply. It's interesting to know that in-process provider has been introduced lately. I saw there were Go and Java in-process providers in the doc, do you also have Node.js in-process provider? Thanks.

**Comment by beeme1mr** [comment]
Hey @yangzhaox, yes we plan on building a node.js in-process provider next. @toddbaert could you provide a link to the issue when you have a moment?

**Comment by toddbaert** [comment]
Hey @beeme1mr and @yangzhaox . [Here](https://github.com/open-feature/js-sdk-contrib/issues/614) is the issue. It's a big one and will not be implemented in a single PR.

**Comment by yangzhaox** [comment]
As to reading flag config, gRPC is the default protocol, is http(s) also supported for regular pulling?

**Comment by toddbaert** [comment]
> As to getting the flag definition, gRPC is the default protocol, is http(s) also supported for periodically pulling? @toddbaert

Currently in-process providers support only gRPC sources.

**Comment by yangzhaox** [comment]
Hi @toddbaert, it's great to see that the [node.js in-process provider](https://github.com/open-feature/js-sdk-contrib/pull/633) has been completed. Do you have any doc guiding me to connect the in-process provider to a flagd instance through gRPC? And how to configure / start flagd so it can act as a gPRC server streaming its flag definition? I read through the doc but could not figure out myself.

**Comment by toddbaert** [comment]
Currently, in process providers can only get their flags from a compatible gRPC server (a server implementing the [sync.proto](https://buf.build/open-feature/flagd/docs/main:flagd.sync.v1)).

There's only one current open source implementation of this, which is [flagd-proxy](https://github.com/open-feature/flagd/tree/main/flagd-proxy). Unlike flagd, flagd-proxy is not general purpose; it was designed expressly to be used as part of the [OpenFeature Operator](https://github.com/open-feature/open-feature-operator) aka OFO, which defines flags as CRDs. So basically, flagd proxy would read flag CRDs in Kubernetes, and expose them via gRPC to in-process providers. OFO basically handles most of this for you.

If you're not using Kubernetes/OFO, you'll need some other implementation of the [sync.proto](https://buf.build/open-feature/flagd/docs/main:flagd.sync.v1)). Some adopters have built this themselves, and also built some associated UI to configure flags, and then their in process providers connect to this custom server.

So this leaves you with 2 options:

- use OFO (requires Kubernetes)
- build your own custom flag server which exposes a [sync.proto](https://buf.build/open-feature/flagd/docs/main:flagd.sync.v1)) implementation (significant effort)

Do either of these work for you?

If these don't satisfy your needs, we can consider 2 improvements to our offerings:

1. **expose a sync.proto implementation on flagd itself**, so that you could use flagd to serve "unevaluated" flags to in-process providers (effectively adding flagd-proxy's functionality to flagd) but backing it with flagd's multi-source paradigm (file, HTTP, etc, sources)
1. a**dd features to every in-process provider to enable them to read arbitrary sources**, not just gRPC sync.protos (ex: files, HTTP, etc).

At first glance, I think option 2 will be way too much duplicated effort across every in-process provider implementation. Option 1 seems more feasible.

What do you think?

**Comment by yangzhaox** [comment]
Hi @toddbaert, thanks for the comprehensive reply, really appreciated it. 

We use k8s with multi-clusters in multi-DCs, OFO sounds a bit overkill to me, but maybe I don't have a clear picture how it works. Do you have any diagram or doc for that?

I'm interested in the custom flag server approach, as well as the UI to configure the flags. Is there any open source implementation I can refer?

Among the 2 options, I like the option 1 more because it makes flagd more powerful, and give users more choices. One can use rpc evaluation, in-process evaluation or both. The downside is flagd is getting a lit more complicated to maintain. 

The 3rd option could be providing a separate flag server, something like flagd-proxy but not tired to k8s. It reads flags from different sources and then broadcast changes to all connected in-process providers. And it does not do rpc evaluation.

**Comment by toddbaert** [comment]
> We use k8s with multi-clusters in multi-DCs, OFO sounds a bit overkill to me, but maybe I don't have a clear picture how it works. Do you have any diagram or doc for that?

See the OFO doc [here](https://github.com/open-feature/open-feature-operator/tree/main/docs), specifically the "concepts" section. There's also a [specific section on how flagd-proxy fits in](https://github.com/open-feature/open-feature-operator/blob/main/docs/flagd_proxy.md).

> I'm interested in the custom flag server approach, as well as the UI to configure the flags. Is there any open source implementation I can refer?

There's no such open-source implementation (though I know there are closed-source ones). One of the "non-goals" of the project is to build a UI for feature-flag or flagd configuration. We have a lot of associated vendors that do a great job with their UIs and are compatible with open-feature SDKs. An open source implementation for such a UI is outside the scope of the project. That wouldn't stop anyone else from building such a solution though.

> Among the 2 options, I like the option 1 more because it makes flagd more powerful, and give users more choices. One can use rpc evaluation, in-process evaluation or both. The downside is flagd is getting a bit more complicated to maintain.

Agreed on all counts. Though there's a bit of additional complexity here, I don't think it would be unmanageable. We've already designed the interfaces and protos, so implementation should be straightforward.

> The 3rd option could be providing a separate flag server, something like flagd-proxy but not tired to k8s. It reads flags from different sources and then broadcast changes to all connected in-process providers. And it does not do rpc evaluation.

This feels very much like flagd-proxy, but "bigger", general purpose, and more flexible, which is basically what flagd already is, which is why I keep going back to option 1, especially considering we don't want to build a UI or API for configuring flags.

**Comment by yangzhaox** [comment]
Hi @toddbaert awesome news! Thank you all for making this happen, I'll find time to test it out.
